DLBC_GWINNETT/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    url(r'^adminG/', include(admin.site.urls)),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^about_us/', include('about_us.urls', namespace='about_us')),
    url(r'^leadership/', include('leadership.urls', namespace='leadership')),
    url(r'^contact/', include('contact_us.urls', namespace='contact')),
    url(r'^ministries/', include('ministries.urls', namespace='ministries')),
    url(r'^sermons/', include('sermons_live.urls', namespace='sermons')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^live/', include('livestream.urls', namespace='livestream')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

leadership/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.leader_list, name='leadership_list'),
    url(r'^(?P<leader_slug>[-\w]+)/$', views.leader_list, name='leadership_list_by_name'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.leader_detail, name='leader_detail'),
]

sermons_live/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.sermon_list, name='sermon_list'),
    url(r'^(?P<sermon_slug>[-\w]+)/$', views.sermon_list, name='sermon_list_by_name'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.sermon_det, name='sermon_detail'),
]

sermons_live/models.py
from django.db import models
from django.core.urlresolvers import reverse
from leadership.models import Leadership


class Sermon(models.Model):
    name = models.CharField(max_length=200, db_index=True)  # adding db_index will help optimize lookups on this field
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)  # This is to order the database in ascending order of name
        verbose_name = 'sermon'  # in the admin site this is what will show in the model and not mangled python name
        verbose_name_plural = 'sermons'

    def __str__(self):
        # this is what is returned whenever a model instance is needed and coerced to be displayed as plain string

        return self.name

    def get_absolute_url(self):
        return reverse('sermons:sermon_list_by_name', args=[self.slug])


class Sermon_details(models.Model):
    sermon_name = models.ForeignKey(Sermon, related_name='sermons_details', blank=True)
    slug = models.SlugField(max_length=200, db_index=True)
    preacher_name = models.ForeignKey(Leadership, related_name='leaders_details', blank=True)
    image = models.ImageField(blank=True)
    details = models.TextField(blank=True)
    text = models.CharField(max_length=100)
    audio_link = models.CharField(max_length=200, blank=True)
    video_link = models.CharField(max_length=200, blank=True)
    download_link = models.CharField(max_length=200, blank=True)
    date = models.DateTimeField()
    recent = models.BooleanField(default=False)

    class Meta:
        ordering = ('sermon_name',)
        verbose_name = 'detail'  # in the admin site this is what will show in the model and not mangled python name
        verbose_name_plural = 'details'
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('sermons:sermon_detail', args=[self.id, self.slug])

sermons_live/views.py
from django.shortcuts import render, get_object_or_404
from .models import Sermon, Sermon_details
from leadership.models import LeaderBio


def sermon_list(request, sermon_slug=None):
    sermon = None
    sermons = Sermon.objects.all()
    sermons_details = Sermon_details.objects.all()
    if sermon_slug:
        sermon = get_object_or_404(Sermon, slug=sermon_slug)
        sermons_details = sermons_details.filter(sermon=sermon)

    return render(request, 'sermon/sermon.html', {'sermon': sermon, 'sermons': sermons,
                                                           'sermons_details': sermons_details,
                                                            })


def sermon_det(request, id, slug, sermon_slug=None):
    sermon_detail = get_object_or_404(Sermon_details, id=id, slug=slug)
    sermon = None
    sermons = Sermon.objects.all()
    leaders = LeaderBio.objects.all()

    if sermon_slug:
        sermon = get_object_or_404(Sermon, slug=sermon_slug)

    return render(request, 'sermon/sermon_details.html', {'sermon_detail': sermon_detail, 'sermon': sermon,
                                                               'leaders': leaders, 'sermons': sermons, })




sermons_live/templates/sermon/sermon.html
{% extends "home/base.html" %}
{% load static %}

{% block title %}
    Sermons
{% endblock %}

{% block content %}
<div>
    <br>
</div>

    <!-- - - - - - - - - - - - - - Breadcrumbs - - - - - - - - - - - - - - - - -->

    <div class="breadcrumbs-wrap style-2 align-center" style="margin-top: -30px;">

      <div class="container wide" style="padding-top: 80px;">

        <h1 class="page-title">Sermons</h1>

        <ul class="breadcrumbs">

          <li><a href="{% url "home:index" %}">Home</a></li>
          <li>Sermons</li>

        </ul>

      </div>

    </div>

    <!-- - - - - - - - - - - - - end Breadcrumbs - - - - - - - - - - - - - - - -->



<!-- - - - - - - - - - - - - - Content - - - - - - - - - - - - - - - - -->

    <div id="content" class="page-content-wrap">

      <div class="container wide">

        <div class="sorting">


        </div>

        <div class="entry-box flex-row item-col-3">

          <!-- Entry -->
            {% for s in sermons_details %}
          <div class="entry-col">

            <div class="entry">

              <!-- - - - - - - - - - - - - - Entry attachment - - - - - - - - - - - - - - - - -->
              <div class="thumbnail-attachment">
                <a href="{{ s.get_absolute_url }}"><img src="{{ s.image.url }}" alt=""></a>
              </div>

              <!-- - - - - - - - - - - - - - Entry body - - - - - - - - - - - - - - - - -->
              <div class="entry-body">

                <h5 class="entry-title"><a href="#">{{ s.sermon_name }}</a></h5>
                <div class="entry-meta">

                  <span>on</span>
                  <time class="entry-date" datetime="2018-03-18">{{ s.date }}</time>
                  <span>by</span>
                  <a href="{{ s.get_absolute_url }}" class="entry-cat">{{ s.preacher_name }}</a>

                </div>
                <p>{{ s.details }}</p>

                <div class="entry-action">

                  <a href="{{ s.get_absolute_url }}"><i class="licon-camera-play"></i></a>
                  <a href="{{ s.get_absolute_url }}"><i class="licon-headphones"></i></a>
                  <a href="{{ s.get_absolute_url }}"><i class="licon-enter-down2"></i></a>
                  <a href="{{ s.get_absolute_url }}"><i class="licon-file-empty"></i></a>

                </div>

              </div>

            </div>

          </div>
            {% endfor %}

          <!-- Entry -->

          <!-- Entry -->


          <!-- Entry -->


          <!-- Entry -->

          <!-- Entry -->

          <!-- Entry -->

          <!-- Entry -->

          <!-- Entry -->

        </div>


      </div>

    </div>

    <!-- - - - - - - - - - - - - end Content - - - - - - - - - - - - - - - -->



{% endblock %}

{% block scripts %}

    <!-- {{ block.super }} -->

{% endblock %}

sermons_live/templates/sermon/sermon_details.html
{% extends "home/base.html" %}
{% load static %}

{% block title %}
    Contact US
{% endblock %}

{% block content %}
<div>
    <br>
</div>

    <!-- - - - - - - - - - - - - - Breadcrumbs - - - - - - - - - - - - - - - - -->

    <div class="breadcrumbs-wrap style-2 align-center" style="margin-top: -30px;">

      <div class="container wide" style="padding-top: 80px;">

        <h1 class="page-title">{{ sermon_detail.sermon_name }}</h1>

        <ul class="breadcrumbs">

          <li><a href="{% url "home:index" %}">Home</a></li>
          <li><a href="{% url "sermons:sermon_list" %}">Sermons</a></li>
          <li>{{ sermon_detail.sermon_name }}</li>

        </ul>

      </div>

    </div>

    <!-- - - - - - - - - - - - - end Breadcrumbs - - - - - - - - - - - - - - - -->



<!-- - - - - - - - - - - - - - Content - - - - - - - - - - - - - - - - -->

    <div id="content" class="page-content-wrap">

      <div class="container wide">

        <h1 class="align-center">{{ sermon_detail.sermon_name }}</h1>

        <div class="content-element">

          <div class="single-post">

            <div class="content-element3">
              <img src="{{ sermon_detail.image.url }}" alt="">
            </div>

            <div class="content-element4">

              <div class="row">
                <div class="col-md-8">

                  <h5 class="e-title">Description</h5>

                  <p>{{ sermon_detail.details }}</p>

                  <div class="btns-set content-element4">

                    <a href="{{ sermon_detail.video_link }}" class="btn"><i class="licon-camera-play"></i>Watch</a>
                    <a href="{{ sermon_detail.audio_link }}" class="btn"><i class="licon-headphones"></i>Listen</a>
                    <a href="{{ sermon_detail.video_link }}" class="btn"><i class="licon-enter-down2"></i>Download</a>


                  </div>

                  <div class="share-wrap">

                    <span class="share-title">Share this:</span>
                    <ul class="social-icons share">

                      <li><a href="#" class="sh-facebook"><i class="fab fa-facebook-square"></i></a></li>
                      <li><a href="#" class="sh-twitter"><i class="fab fa-twitter-square"></i></a></li>
                      <li><a href="#" class="sh-google"><i class="fab fa-instagram"></i></a></li>
                      <li><a href="#" class="sh-mail"><i class="fas fa-envelope"></i></a></li>

                    </ul>

                  </div>

                </div>
                <div class="col-md-4">

                  <h5 class="e-title">Details</h5>

                  <ul class="custom-list">

                    <li><span>Date:</span> {{ sermon_detail.date }}</li>
                    <li><span>Topics:</span> <a href="{{ sermon_detail.get_absolute_url }}">{{ sermon_detail.sermon_name }}</a></li>
                    <li><span>Pastor:</span> <a href="{% url "leadership:leadership_list" %}">{{ sermon_detail.preacher_name }}</a></li>
                    <li><span>Books:</span> <a href="{{ sermon_detail.get_absolute_url }}" class="link-text">{{ sermon_detail.text }}</a></li>

                  </ul>

                </div>
              </div>

            </div>

            <div class="page-nav">
{#              <div class="flex-item"><a href="#" class="btn btn-small btn-style-6 prev-btn">Previous Event</a></div>#}
              <a href="#" class="menu-button"><i class="licon-icons"></i></a>
{#              <div class="flex-item"><a href="#" class="btn btn-small btn-style-6 next-btn">Next Event</a></div>#}
            </div>

          </div>

        </div>

{#        <h3 class="title">Related Sermons</h3>#}



      </div>

    </div>

    <!-- - - - - - - - - - - - - end Content - - - - - - - - - - - - - - - -->



{% endblock %}

{% block scripts %}

    <!-- {{ block.super }} -->

{% endblock %}