DLBC_GWINNETT/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    url(r'^adminG/', include(admin.site.urls)),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^about_us/', include('about_us.urls', namespace='about_us')),
    url(r'^leadership/', include('leadership.urls', namespace='leadership')),
    url(r'^contact/', include('contact_us.urls', namespace='contact')),
    url(r'^ministries/', include('ministries.urls', namespace='ministries')),
    url(r'^sermons/', include('sermons_live.urls', namespace='sermons')),
    url(r'^events/', include('events.urls', namespace='events')),
    url(r'^live/', include('livestream.urls', namespace='livestream')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

events/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.event_list, name='event_list'),
    url(r'^(?P<event_slug>[-\w]+)/$', views.event_list, name='event_list_by_name'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.event_det, name='event_detail'),
]

home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

ministries/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.ministry_list, name='ministry_list'),
    url(r'^(?P<ministry_slug>[-\w]+)/$', views.ministry_list, name='ministry_list_by_name'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ministry_det, name='ministry_detail'),
]

ministries/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Ministry(models.Model):
    name = models.CharField(max_length=200, db_index=True)  # adding db_index will help optimize lookups on this field
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)  # This is to order the database in ascending order of name
        verbose_name = 'ministry'  # in the admin site this is what will show in the model and not mangled python name
        verbose_name_plural = 'ministries'

    def __str__(self):
        # this is what is returned whenever a model instance is needed and coerced to be displayed as plain string

        return self.name

    def get_absolute_url(self):
        return reverse('ministries:ministry_list_by_name', args=[self.slug])


class Ministry_details(models.Model):
    ministry_name = models.ForeignKey(Ministry, related_name='ministries_details', blank=True)
    slug = models.SlugField(max_length=200, db_index=True)
    Age = models.CharField(max_length=200, blank=True)
    image = models.ImageField(blank=True)
    details = models.TextField(blank=True)

    class Meta:
        ordering = ('ministry_name',)
        verbose_name = 'detail'  # in the admin site this is what will show in the model and not mangled python name
        verbose_name_plural = 'details'
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('ministries:ministry_detail', args=[self.id, self.slug])

ministries/views.py
from django.shortcuts import render, get_object_or_404
from .models import Ministry_details, Ministry
from leadership.models import LeaderBio
from events.models import Event_details


def ministry_list(request, ministry_slug=None):
    ministry = None
    ministries = Ministry.objects.all()
    ministries_details = Ministry_details.objects.all()
    if ministry_slug:
        ministry = get_object_or_404(Ministry, slug=ministry_slug)
        ministries_details = ministries_details.filter(ministry=ministry)

    return render(request, 'ministries/ministry_list.html', {'ministry': ministry, 'ministries': ministries,
                                                           'ministries_details': ministries_details,
                                                            })


def ministry_det(request, id, slug, ministry_slug=None):
    ministry_detail = get_object_or_404(Ministry_details, id=id, slug=slug)
    ministry = None
    ministries = Ministry.objects.all()
    leaders = LeaderBio.objects.all()
    events = Event_details.objects.all()

    if ministry_slug:
        ministry = get_object_or_404(Ministry, slug=ministry_slug)

    return render(request, 'ministries/ministry_detail.html', {'ministry_detail': ministry_detail, 'ministry': ministry,
                                                               'leaders': leaders, 'ministries': ministries, 'events': events})




ministries/templates/ministries/ministry_detail.html
{% extends "home/base.html" %}
{% load static %}

{% block title %}
    {{ ministry_detail.ministry_name }}
{% endblock %}

{% block content %}
<div>
    <br>
</div>

    <!-- - - - - - - - - - - - - - Breadcrumbs - - - - - - - - - - - - - - - - -->

    <div class="breadcrumbs-wrap style-2 align-center" style="margin-top: -30px;">

      <div class="container wide" style="padding-top: 80px;">

        <h1 class="page-title">{{ ministry_detail.ministry_name }}</h1>

        <ul class="breadcrumbs">

          <li><a href="{% url "home:index" %}">Home</a></li>
          <li><a href="{% url "ministries:ministry_list" %}">Ministries</a></li>
          <li>{{ ministry_detail.ministry_name }}</li>

        </ul>

      </div>

    </div>

    <!-- - - - - - - - - - - - - end Breadcrumbs - - - - - - - - - - - - - - - -->

<!-- - - - - - - - - - - - - - Content - - - - - - - - - - - - - - - - -->

    <div id="content" class="page-content-wrap">

      <div class="container wide">

        <h1>{{ ministry_detail.ministry_name }}</h1>

        <div class="row">

          <main id="main" class="col-lg-9">

            <figure class="content-element3">
              <img src="{{ ministry_detail.image.url }}" alt="">
            </figure>

            <div class="content-element3">

              <p>{{ ministry_detail.details }}</p>


            </div>

            <div class="content-element3">


            <div class="share-wrap">

              <span class="share-title">Share this:</span>
              <ul class="social-icons share">

                <li><a href="#" class="sh-facebook"><i class="fab fa-facebook-square"></i></a></li>
                <li><a href="#" class="sh-twitter"><i class="fab fa-twitter-square"></i></a></li>
                <li><a href="#" class="sh-pinterest"><i class="fab fa-instagram"></i></a></li>
                <li><a href="#" class="sh-mail"><i class="fas fa-envelope"></i></a></li>

              </ul>

            </div>

          </main>
          <aside id="sidebar" class="col-lg-3">

            <div class="widget">

              <h5 class="widget-title">Leadership</h5>

              <div class="entry-box entry-small">

                <!-- Entry -->
                <div class="entry-col">
                    {% for leader in leaders %}

                  <div class="entry">
                    {% if leader.Leader_ministry == ministry_detail.ministry_name or leader.Leader_ministry == 'All'%}
                    <!-- - - - - - - - - - - - - - Entry attachment - - - - - - - - - - - - - - - - -->
                    <div class="thumbnail-attachment">
                      <a href="{{ leader.get_absolute_url }}"><img src="{{ leader.leader_image.url }}" alt=""></a>
                    </div>

                    <!-- - - - - - - - - - - - - - Entry body - - - - - - - - - - - - - - - - -->
                    <div class="entry-body">

                      <h6 class="entry-title"><a href="{{ leader.get_absolute_url }}">{{ leader.leader_name }}</a></h6>
                      <div class="entry-meta">

                        <span>{{ leader.leader_position }}</span>

                      </div>

                    </div>
                    {% endif %}
                  </div>
                 {% endfor %}

                </div>

            </div>

            <div class="widget">

              <h5 class="widget-title">Other Ministries</h5>

              <ul class="custom-list style-2">
                  {% for ministry in ministries %}
                <li><a href="{% url "ministries:ministry_list" %}">{{ ministry.name }}</a></li>
                {% endfor %}
              </ul>

            </div>

            <div class="widget">

              <h5 class="widget-title">Upcoming Events</h5>
              <div class="event-box style-2">
                {% for event in events %}
                    {% if event.ministry_name == ministry.name %}
                <!-- Event -->
                <div class="event">

                  <div class="event-date">

                    <h3 class="numb">{{ event.start_date.month }}</h3>
                    <h6 class="month">{{ event.start_date.day }}</h6>

                  </div>

                  <div class="event-body">

                    <h6 class="event-title"><a href="#">{{ event.event_name }}</a></h6>

                    <p class="e-info">{{ event.start_time }} - {{ event.end_time }} {{ event.venue_name }}</p>

                  </div>

                </div>
                    {% endif %}
                  {% endfor %}

                <!-- Event -->

                <!-- Event -->

              </div>

              <a href="{% url "events:event_list" %}" class="btn btn-small btn-style-6">More Events</a>

            </div>

          </aside>

        </div>

      </div>

    </div>

    <!-- - - - - - - - - - - - - end Content - - - - - - - - - - - - - - - -->




{% endblock %}

{% block scripts %}

    <!-- {{ block.super }} -->

{% endblock %}

ministries/templates/ministries/ministry_list.html
{% extends "home/base.html" %}
{% load static %}

{% block title %}
    Ministries
{% endblock %}

{% block content %}
<div>
    <br>
</div>

    <!-- - - - - - - - - - - - - - Breadcrumbs - - - - - - - - - - - - - - - - -->

    <div class="breadcrumbs-wrap style-2 align-center" style="margin-top: -30px;">

      <div class="container wide" style="padding-top: 80px;">

        <h1 class="page-title">Ministries</h1>

        <ul class="breadcrumbs">

          <li><a href="{% url "home:index" %}">Home</a></li>
          <li>Ministries</li>

        </ul>

      </div>

    </div>

    <!-- - - - - - - - - - - - - end Breadcrumbs - - - - - - - - - - - - - - - -->


<!-- - - - - - - - - - - - - - Content - - - - - - - - - - - - - - - - -->

    <div id="content" class="page-content-wrap">

      <div class="container wide">

        <div class="icons-box style-2 type-2 flex-row item-col-3">
            {% for ministry_detail in ministries_details %}
          <div class="fx-col">

            <!-- - - - - - - - - - - - - - Icon Box Item - - - - - - - - - - - - - - - - -->
            <div class="icons-wrap">

              <div class="bg-img" data-bg="{{ ministry_detail.image.url }}" style="background-image: url(&quot;images/430x420_img1.jpg&quot;);"></div>

              <div class="icons-item">
                <div class="item-box">
                  <h4 class="icons-box-title"><a href="{{ ministry_detail.get_absolute_url }}">{{ ministry_detail.ministry_name }}</a></h4>
                  <p>Ages {{ ministry_detail.Age }}</p>
                </div>
              </div>

            </div>

          </div>
            {% endfor %}


        </div>

      </div>

    </div>

    <!-- - - - - - - - - - - - - end Content - - - - - - - - - - - - - - - -->



{% endblock %}

{% block scripts %}

    <!-- {{ block.super }} -->

{% endblock %}